# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.
  
[[main]]
  name = "Schedule and Lecture Notes"
  url = "lecture-notes"
  weight = 1
  
[[main]]
  name = "Assignments and Grading"
  url = "assignments"
  weight = 2
  
[[main]]
  name = "rstudio.cloud"
  url = "https://rstudio.cloud"
  weight = 3


# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/media/resume.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "media/resume.pdf"
#    weight = 70
